export type ShipmozoZoneRates = {
  zoneA: number
  zoneB: number
  zoneC: number
  zoneD: number
  zoneE: number
}

export type ShipmozoB2CRateCardSeed = {
  aliases: string[]
  mode: 'air' | 'surface'
  minWeight: number
  type: 'forward' | 'rto'
  baseRates: ShipmozoZoneRates
  additionalRates?: ShipmozoZoneRates | null
  additionalWeightUnit?: number | null
  codCharges?: number | null
  codPercent?: number | null
  otherCharges?: number | null
}

export const SHIPMOZO_B2C_RATE_CARD_DATA: ShipmozoB2CRateCardSeed[] = [
  {
    aliases: ['Delhivery Air'],
    mode: 'air',
    minWeight: 0.5,
    type: 'forward',
    baseRates: { zoneA: 37, zoneB: 51, zoneC: 63, zoneD: 70, zoneE: 83 },
    additionalRates: { zoneA: 34, zoneB: 40, zoneC: 56, zoneD: 56, zoneE: 74 },
    additionalWeightUnit: 0.5,
    codCharges: 39,
    codPercent: 1.8,
    otherCharges: 0,
  },
  {
    aliases: ['Delhivery Surface'],
    mode: 'surface',
    minWeight: 0.5,
    type: 'forward',
    baseRates: { zoneA: 30, zoneB: 41, zoneC: 47, zoneD: 53, zoneE: 65 },
    additionalRates: { zoneA: 28, zoneB: 36, zoneC: 43, zoneD: 43, zoneE: 63 },
    additionalWeightUnit: 0.5,
    codCharges: 39,
    codPercent: 1.8,
    otherCharges: 0,
  },
  {
    aliases: ['Delhivery Surface 10 K.G', 'Delhivery Surface 10kg'],
    mode: 'surface',
    minWeight: 10,
    type: 'forward',
    baseRates: { zoneA: 166, zoneB: 231, zoneC: 278, zoneD: 290, zoneE: 410 },
    additionalRates: { zoneA: 16, zoneB: 19, zoneC: 22, zoneD: 24, zoneE: 30.5 },
    additionalWeightUnit: 1,
    codCharges: 35,
    codPercent: 1.5,
    otherCharges: 0,
  },
  {
    aliases: ['Delhivery Surface 5 K.G', 'Delhivery Surface 5kg'],
    mode: 'surface',
    minWeight: 5,
    type: 'forward',
    baseRates: { zoneA: 150, zoneB: 161, zoneC: 174, zoneD: 197, zoneE: 231 },
    additionalRates: { zoneA: 29, zoneB: 31, zoneC: 33, zoneD: 39, zoneE: 45 },
    additionalWeightUnit: 1,
    codCharges: 38,
    codPercent: 1.8,
    otherCharges: 0,
  },
  {
    aliases: ['Delhivery Surface 20 K.G', 'Delhivery Surface 20kg'],
    mode: 'surface',
    minWeight: 20,
    type: 'forward',
    baseRates: { zoneA: 296, zoneB: 421, zoneC: 462, zoneD: 525, zoneE: 694 },
    additionalRates: { zoneA: 15, zoneB: 19, zoneC: 21, zoneD: 23, zoneE: 31.5 },
    additionalWeightUnit: 1,
    codCharges: 35,
    codPercent: 1.5,
    otherCharges: 0,
  },
  {
    aliases: ['Delhivery Surface 2 Kgs'],
    mode: 'surface',
    minWeight: 2,
    type: 'forward',
    baseRates: { zoneA: 78, zoneB: 87, zoneC: 95, zoneD: 99, zoneE: 126 },
    additionalRates: { zoneA: 30, zoneB: 32, zoneC: 34, zoneD: 35, zoneE: 51 },
    additionalWeightUnit: 1,
    codCharges: 30,
    codPercent: 1.5,
    otherCharges: 0,
  },
  {
    aliases: ['Delhivery Surface DS 1 Kg'],
    mode: 'surface',
    minWeight: 1,
    type: 'forward',
    baseRates: { zoneA: 52, zoneB: 61, zoneC: 68, zoneD: 74, zoneE: 100 },
    additionalRates: { zoneA: 33, zoneB: 34, zoneC: 35, zoneD: 35, zoneE: 44 },
    additionalWeightUnit: 1,
    codCharges: 34,
    codPercent: 1.7,
    otherCharges: 0,
  },
  {
    aliases: ['Xpressbees Surface'],
    mode: 'surface',
    minWeight: 0.5,
    type: 'forward',
    baseRates: { zoneA: 33, zoneB: 37, zoneC: 40, zoneD: 43, zoneE: 59 },
    additionalRates: { zoneA: 18, zoneB: 21, zoneC: 26, zoneD: 31, zoneE: 38 },
    additionalWeightUnit: 0.5,
    codCharges: 27,
    codPercent: 1.5,
    otherCharges: 0,
  },
  {
    aliases: ['Xpressbees 5 K.G'],
    mode: 'surface',
    minWeight: 5,
    type: 'forward',
    baseRates: { zoneA: 128, zoneB: 153, zoneC: 163, zoneD: 173, zoneE: 226 },
    additionalRates: { zoneA: 21, zoneB: 25, zoneC: 30, zoneD: 37, zoneE: 40 },
    additionalWeightUnit: 1,
    codCharges: 32,
    codPercent: 1.8,
    otherCharges: 0,
  },
  {
    aliases: ['Xpressbees 10 K.G'],
    mode: 'surface',
    minWeight: 10,
    type: 'forward',
    baseRates: { zoneA: 159, zoneB: 198, zoneC: 266, zoneD: 275, zoneE: 360 },
    additionalRates: { zoneA: 16, zoneB: 20, zoneC: 26, zoneD: 29, zoneE: 36 },
    additionalWeightUnit: 1,
    codCharges: 30,
    codPercent: 1.5,
    otherCharges: 0,
  },
  {
    aliases: ['Xpressbees 1 K.G'],
    mode: 'surface',
    minWeight: 1,
    type: 'forward',
    baseRates: { zoneA: 37, zoneB: 46, zoneC: 54, zoneD: 64, zoneE: 83 },
    additionalRates: { zoneA: 19, zoneB: 23, zoneC: 28, zoneD: 32, zoneE: 39 },
    additionalWeightUnit: 0.5,
    codCharges: 28,
    codPercent: 1.5,
    otherCharges: 0,
  },
  {
    aliases: ['Xpressbees 2 K.G', 'Xpressbees Surface 2kg'],
    mode: 'surface',
    minWeight: 2,
    type: 'forward',
    baseRates: { zoneA: 50, zoneB: 60, zoneC: 73, zoneD: 75, zoneE: 88 },
    additionalRates: { zoneA: 25, zoneB: 30, zoneC: 36, zoneD: 38, zoneE: 44 },
    additionalWeightUnit: 1,
    codCharges: 31,
    codPercent: 1.6,
    otherCharges: 0,
  },
  {
    aliases: ['Amazon Prepaid Surface 500g', 'Amazon COD Surface 500gm'],
    mode: 'surface',
    minWeight: 0.5,
    type: 'forward',
    baseRates: { zoneA: 30, zoneB: 34, zoneC: 41, zoneD: 43, zoneE: 56 },
    additionalRates: { zoneA: 22, zoneB: 26, zoneC: 31, zoneD: 35, zoneE: 40 },
    additionalWeightUnit: 0.5,
    codCharges: 28,
    codPercent: 1.5,
    otherCharges: 0,
  },
  {
    aliases: ['Amazon Shipping Surface 10kg'],
    mode: 'surface',
    minWeight: 10,
    type: 'forward',
    baseRates: { zoneA: 178, zoneB: 200, zoneC: 220, zoneD: 249, zoneE: 338 },
    additionalRates: { zoneA: 12, zoneB: 13, zoneC: 14, zoneD: 16, zoneE: 21 },
    additionalWeightUnit: 1,
    codCharges: 25,
    codPercent: 1.5,
    otherCharges: 0,
  },
  {
    aliases: ['Amazon Shipping Surface 1kg', 'Amazon Shipping'],
    mode: 'surface',
    minWeight: 1,
    type: 'forward',
    baseRates: { zoneA: 31, zoneB: 37, zoneC: 42, zoneD: 46, zoneE: 62 },
    additionalRates: { zoneA: 14, zoneB: 16, zoneC: 18, zoneD: 19, zoneE: 25 },
    additionalWeightUnit: 0.5,
    codCharges: 26,
    codPercent: 1.5,
    otherCharges: 0,
  },
  {
    aliases: ['TCI Express 5kg+', 'TCI Express'],
    mode: 'surface',
    minWeight: 5,
    type: 'forward',
    baseRates: { zoneA: 108, zoneB: 126, zoneC: 138, zoneD: 144, zoneE: 216 },
    additionalRates: { zoneA: 20.5, zoneB: 24, zoneC: 25, zoneD: 26.5, zoneE: 36 },
    additionalWeightUnit: 1,
    codCharges: 29,
    codPercent: 1.6,
    otherCharges: 0,
  },
  {
    aliases: ['Shadowfax', 'Shadowfax Surface'],
    mode: 'surface',
    minWeight: 0.5,
    type: 'forward',
    baseRates: { zoneA: 28, zoneB: 35, zoneC: 37, zoneD: 44, zoneE: 54 },
    additionalRates: { zoneA: 23, zoneB: 28, zoneC: 31, zoneD: 33, zoneE: 43 },
    additionalWeightUnit: 0.5,
    codCharges: 27,
    codPercent: 1.65,
    otherCharges: 0,
  },
  {
    aliases: ['Shadowfax Surface 2Kg', 'Shadowfax-Surface 2 K.G'],
    mode: 'surface',
    minWeight: 2,
    type: 'forward',
    baseRates: { zoneA: 50, zoneB: 50, zoneC: 60, zoneD: 60, zoneE: 98 },
    additionalRates: { zoneA: 21, zoneB: 24, zoneC: 35, zoneD: 35, zoneE: 36 },
    additionalWeightUnit: 1,
    codCharges: 25,
    codPercent: 1.5,
    otherCharges: 0,
  },
  {
    aliases: ['Ekart', 'Ekart Logistics Surface'],
    mode: 'surface',
    minWeight: 0.5,
    type: 'forward',
    baseRates: { zoneA: 33, zoneB: 37, zoneC: 40, zoneD: 44, zoneE: 59 },
    additionalRates: { zoneA: 22, zoneB: 31, zoneC: 31, zoneD: 32, zoneE: 43 },
    additionalWeightUnit: 0.5,
    codCharges: 29.5,
    codPercent: 1.8,
    otherCharges: 0,
  },
  {
    aliases: ['Ekart 1 K.G'],
    mode: 'surface',
    minWeight: 1,
    type: 'forward',
    baseRates: { zoneA: 47, zoneB: 54, zoneC: 61, zoneD: 66, zoneE: 87 },
    additionalRates: { zoneA: 17, zoneB: 17, zoneC: 21, zoneD: 23, zoneE: 30 },
    additionalWeightUnit: 0.5,
    codCharges: 29.5,
    codPercent: 1.8,
    otherCharges: 0,
  },
  {
    aliases: ['Ekart 5 K.G', 'Ekart Surface 5kg'],
    mode: 'surface',
    minWeight: 5,
    type: 'forward',
    baseRates: { zoneA: 100, zoneB: 130, zoneC: 140, zoneD: 140, zoneE: 210 },
    additionalRates: { zoneA: 18, zoneB: 24, zoneC: 24, zoneD: 28, zoneE: 40 },
    additionalWeightUnit: 1,
    codCharges: 30,
    codPercent: 1.5,
    otherCharges: 0,
  },
  {
    aliases: ['Ekart Logistics Surface_Stressed'],
    mode: 'surface',
    minWeight: 1,
    type: 'forward',
    baseRates: { zoneA: 55, zoneB: 60, zoneC: 64, zoneD: 66, zoneE: 78 },
    additionalRates: { zoneA: 25, zoneB: 27, zoneC: 28, zoneD: 32, zoneE: 39 },
    additionalWeightUnit: 1,
    codCharges: 27,
    codPercent: 1.6,
    otherCharges: 0,
  },
  {
    aliases: ['Ekart Logistics Air'],
    mode: 'air',
    minWeight: 0.5,
    type: 'forward',
    baseRates: { zoneA: 28, zoneB: 34, zoneC: 55, zoneD: 60, zoneE: 68 },
    additionalRates: { zoneA: 12, zoneB: 16, zoneC: 35, zoneD: 38, zoneE: 50 },
    additionalWeightUnit: 0.5,
    codCharges: 32,
    codPercent: 1.6,
    otherCharges: 0,
  },
  {
    aliases: ['Ekart 2 K.G', 'Ekart Surface 2kg'],
    mode: 'surface',
    minWeight: 2,
    type: 'forward',
    baseRates: { zoneA: 80, zoneB: 85, zoneC: 94, zoneD: 99, zoneE: 115 },
    additionalRates: { zoneA: 25, zoneB: 27, zoneC: 28, zoneD: 32, zoneE: 39 },
    additionalWeightUnit: 1,
    codCharges: 27,
    codPercent: 1.6,
    otherCharges: 0,
  },
  {
    aliases: ['Movin Air 5 Kg', 'Movin'],
    mode: 'air',
    minWeight: 5,
    type: 'forward',
    baseRates: { zoneA: 363, zoneB: 396, zoneC: 418, zoneD: 451, zoneE: 528 },
    additionalRates: { zoneA: 72, zoneB: 75, zoneC: 79, zoneD: 84, zoneE: 105 },
    additionalWeightUnit: 1,
    codCharges: 0,
    codPercent: 0,
    otherCharges: 0,
  },
  {
    aliases: ['India Post - Speed Post Air', 'India Post-Speed Post Air Prepaid'],
    mode: 'air',
    minWeight: 0.5,
    type: 'forward',
    baseRates: { zoneA: 30, zoneB: 60, zoneC: 70, zoneD: 80, zoneE: 90 },
    additionalRates: { zoneA: 10, zoneB: 30, zoneC: 30, zoneD: 40, zoneE: 50 },
    additionalWeightUnit: 0.5,
    codCharges: 28,
    codPercent: 2,
    otherCharges: 0,
  },
  {
    aliases: ['India Post-Business Parcel Surface', 'India Post-Business Parcel Surface Prepaid'],
    mode: 'surface',
    minWeight: 2,
    type: 'forward',
    baseRates: { zoneA: 45, zoneB: 88, zoneC: 105, zoneD: 115, zoneE: 115 },
    additionalRates: { zoneA: 12, zoneB: 24, zoneC: 28, zoneD: 34, zoneE: 38 },
    additionalWeightUnit: 1,
    codCharges: 70,
    codPercent: 2.1,
    otherCharges: 0,
  },
  {
    aliases: ['Delhivery Surface Reverse'],
    mode: 'surface',
    minWeight: 0.5,
    type: 'rto',
    baseRates: { zoneA: 43, zoneB: 55, zoneC: 60, zoneD: 64, zoneE: 92 },
    additionalRates: null,
    additionalWeightUnit: null,
    codCharges: 0,
    codPercent: 0,
    otherCharges: 0,
  },
  {
    aliases: ['Delhivery 10KG Reverse'],
    mode: 'surface',
    minWeight: 10,
    type: 'rto',
    baseRates: { zoneA: 260, zoneB: 306, zoneC: 370, zoneD: 390, zoneE: 540 },
    additionalRates: { zoneA: 23, zoneB: 28, zoneC: 32, zoneD: 36, zoneE: 50 },
    additionalWeightUnit: 1,
    codCharges: 0,
    codPercent: 0,
    otherCharges: 0,
  },
  {
    aliases: ['Delhivery 5KG Reverse', 'Delhivery Reverse Surface 5kg'],
    mode: 'surface',
    minWeight: 5,
    type: 'rto',
    baseRates: { zoneA: 200, zoneB: 220, zoneC: 240, zoneD: 264, zoneE: 320 },
    additionalRates: { zoneA: 37, zoneB: 40, zoneC: 45, zoneD: 46, zoneE: 55 },
    additionalWeightUnit: 1,
    codCharges: 0,
    codPercent: 0,
    otherCharges: 0,
  },
]
